server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://synmkolxijptzm:12a0dbf649c092191c4145ea49f615e71ba36afed998fa72f5190b55b60f50b2@ec2-35-170-85-206.compute-1.amazonaws.com:5432/d45h5sv5obk8t7
    username: synmkolxijptzm
    password: 12a0dbf649c092191c4145ea49f615e71ba36afed998fa72f5190b55b60f50b2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Project created for Dio - Santander bootcamp
